### ISSUE TITLE
Add game enemies and coins.

### ISSUE THREAD

**Issue by estarkey7** [estarkey7/CSIS3700_Project2#3]
We need to create enemies and things that the player is to collect. All these things should be animated.

**Comment by estarkey7** [comment]
In progress...

**Comment by nmroncone** [comment]
Ok, well let me know if it works or any other issues come up. I'll be up for another couple hours working on it anyway. I'm starting to get a pretty good grasp on Allegro. I hate to say that it's not as bad as it seems, but I'm almost enjoying it.

Thanks,
            Nick Roncone

On Apr 29, 2015, at 11:22 PM, Ed Starkey <notifications@github.com<mailto:notifications@github.com>> wrote:

In progress...

##

**Comment by estarkey7** [comment]
Enemies are in and moving. Coins are created, but need to add to world.

**Comment by estarkey7** [comment]
Enemies and coins complete.
